# Using TensorFlow like NumPy
* TensorFlow can be used in a way similar to NumPy for numerical computations, array manipulations, and mathematical operations. 
* TensorFlow like NumPy allows you to benefit from TensorFlow's powerful features such as `automatic differentiation`, `GPU acceleration`, `distributed computing`, and seamless integration with `deep learning frameworks`. This approach is ideal for scientific computing and building complex machine learning models.

## Tensors and operations

* In TensorFlow, `tensors` are fundamental objects that represent data in the computation graph. They flow through operations, allowing for efficient computation and differentiation.

* Tensors are central to TensorFlow's design, enabling efficient and scalable computation in deep learning models. By understanding how to create and manipulate tensors, you can effectively work with TensorFlow's API to build and train sophisticated machine learning models.

* These tensors will be important when we create `custom cost functions`, `custom metrics`, `custom layers`, and more, so let’s see how to create and manipulate them.

### 1. Creating Tensors
* You can create tensors in TensorFlow just like NumPy arrays:

In [3]:
import tensorflow as tf

# Create a constant tensor
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Create a variable tensor (can be updated)
b = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

# Accessing shape, dtype, and ndim
tensor = tf.constant([[1, 2], [3, 4]])
# shape: Attribute that returns the shape of the tensor.
print(tensor.shape)  # Output: (2, 2)
# dtype: Attribute that returns the data type of the tensor.
print(tensor.dtype)  # Output: <dtype: 'int32'>
# ndim: Method that returns the number of dimensions (or rank) of the tensor.
print(tensor.ndim)  # Output: 2

# Create tensors with specified shape and dtype
zeros_tensor = tf.zeros((3, 3), dtype=tf.float32)
ones_tensor = tf.ones((2, 2), dtype=tf.int32)
random_tensor = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

(2, 2)
<dtype: 'int32'>
2


### 2. Indexing
* Indexing refers to accessing individual elements within a tensor using specific indices :

In [4]:
import tensorflow as tf

# Define a 2D tensor
tensor_2d = tf.constant([[1, 2, 3],
                          [4, 5, 6]])

# Accessing individual elements
print(tensor_2d[0, 0])  # Output: 1
print(tensor_2d[1, 2])  # Output: 6

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


### 3. Slicing
* Slicing allows you to extract sub-tensors (slices) from a larger tensor based on specific ranges of indices along each dimension.

In [5]:
import tensorflow as tf

# Slicing along rows and columns
print(tensor_2d[0, :])  # Slice the first row: [1, 2, 3]
print(tensor_2d[:, 1])  # Slice the second column: [2, 5, 8]

# Slicing sub-tensors
print(tensor_2d[1:, :2])  # Slice rows from index 1 onwards and columns up to index 2:
                          # [[4, 5],
                          #  [7, 8]]

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 5], shape=(2,), dtype=int32)
tf.Tensor([[4 5]], shape=(1, 2), dtype=int32)


In [6]:
import tensorflow as tf

# Define a 3D tensor (3x3x3)
tensor_3d = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

# Slicing along different dimensions
print(tensor_3d[1, :, :])  # Slice the entire 2nd 'layer' (2nd matrix)
print(tensor_3d[:, 1, 1])  # Slice the (1, 1) element from each 'layer'
print(tensor_3d[0:2, :, 0])  # Slice the first two 'layers' and extract the first column

tf.Tensor(
[[10 11 12]
 [13 14 15]
 [16 17 18]], shape=(3, 3), dtype=int32)
tf.Tensor([ 5 14 23], shape=(3,), dtype=int32)
tf.Tensor(
[[ 1  4  7]
 [10 13 16]], shape=(2, 3), dtype=int32)


### 4. Arithmetic Operations

In [7]:
import tensorflow as tf

# Define a 2D tensor (3x3)
tensor_a = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)
tensor_b = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Addition: Element-wise addition of two tensors.
result = tf.add(tensor_a, tensor_b)
# Subtraction: Element-wise subtraction of two tensors.
result = tf.subtract(tensor_a, tensor_b)
# Multiplication: Element-wise multiplication of two tensors.
result = tf.multiply(tensor_a, tensor_b)
# Division: Element-wise division of two tensors.
result = tf.divide(tensor_a, tensor_b)
# Exponentiation: Element-wise exponentiation of a tensor.
exponent = 2
result = tf.pow(tensor_a, exponent)

### 5. Broadcasting Basics
* Broadcasting is a technique used in TensorFlow to perform element-wise operations on tensors of different shapes by implicitly aligning their dimensions. The main concept is to extend (or "broadcast") smaller tensors to match the shape of larger tensors before applying element-wise operations.

In [17]:
# Example 1: Broadcasting Scalars
import tensorflow as tf

# Define a tensor with shape (2, 3)
tensor_a = tf.constant([[1, 2, 3],
                         [4, 5, 6]])

# Define a scalar value
scalar_b = tf.constant(2)

# Element-wise multiplication using broadcasting
result = tensor_a * scalar_b

# Display the result
print(result.numpy())

[[ 2  4  6]
 [ 8 10 12]]


In [18]:
# Example 2: Broadcasting Vectors
import tensorflow as tf

# Define a matrix with shape (2, 3)
matrix_a = tf.constant([[1, 2, 3],
                        [4, 5, 6]])

# Define a vector with shape (3,)
vector_b = tf.constant([10, 20, 30])

# Element-wise addition using broadcasting
result = matrix_a + vector_b

# Display the result
print(result.numpy())

[[11 22 33]
 [14 25 36]]


In [19]:
# Example 3: Broadcasting Along Different Axes
import tensorflow as tf

# Define a matrix with shape (2, 3)
matrix_a = tf.constant([[1, 2, 3],
                        [4, 5, 6]])

# Define a vector with shape (2,)
vector_c = tf.constant([10, 20])

# Element-wise multiplication using broadcasting along different axes
result = matrix_a * vector_c[:, tf.newaxis]

# Display the result
print(result.numpy())

[[ 10  20  30]
 [ 80 100 120]]


### 6. Reduction operations
* Reduction operations in TensorFlow are used to compute aggregate values (e.g., sum, mean, maximum, minimum) over specific dimensions of a tensor, resulting in a tensor with reduced dimensions or a scalar value. 

In [20]:
# 1. tf.reduce_sum

import tensorflow as tf

# Define a tensor
tensor = tf.constant([[1, 2, 3],
                       [4, 5, 6]])

# Compute sum along axis 0 (sum of each column)
sum_along_axis0 = tf.reduce_sum(tensor, axis=0)

# Compute sum along axis 1 (sum of each row)
sum_along_axis1 = tf.reduce_sum(tensor, axis=1)

print("Sum along axis 0:", sum_along_axis0.numpy())  # Output: [5 7 9]
print("Sum along axis 1:", sum_along_axis1.numpy())  # Output: [ 6 15]

Sum along axis 0: [5 7 9]
Sum along axis 1: [ 6 15]


In [21]:
# 2. tf.reduce_mean
import tensorflow as tf

# Define a tensor
tensor = tf.constant([[1, 2, 3],
                       [4, 5, 6]])

# Compute mean along axis 0 (mean of each column)
mean_along_axis0 = tf.reduce_mean(tensor, axis=0)

# Compute mean along axis 1 (mean of each row)
mean_along_axis1 = tf.reduce_mean(tensor, axis=1)

print("Mean along axis 0:", mean_along_axis0.numpy())  # Output: [2.5 3.5 4.5]
print("Mean along axis 1:", mean_along_axis1.numpy())  # Output: [2. 5.]

Mean along axis 0: [2 3 4]
Mean along axis 1: [2 5]


In [22]:
# 3. tf.reduce_max and tf.reduce_min
import tensorflow as tf

# Define a tensor
tensor = tf.constant([[1, 2, 3],
                       [4, 5, 6]])

# Compute maximum along axis 0 (maximum of each column)
max_along_axis0 = tf.reduce_max(tensor, axis=0)

# Compute minimum along axis 1 (minimum of each row)
min_along_axis1 = tf.reduce_min(tensor, axis=1)

print("Maximum along axis 0:", max_along_axis0.numpy())  # Output: [4 5 6]
print("Minimum along axis 1:", min_along_axis1.numpy())  # Output: [1 4]

Maximum along axis 0: [4 5 6]
Minimum along axis 1: [1 4]


In [23]:
# 4. tf.math.reduce_std
import tensorflow as tf

# Define a tensor
tensor = tf.constant([[1.0, 2.0, 3.0],
                       [4.0, 5.0, 6.0]])

# Compute the standard deviation across all elements
std_all = tf.math.reduce_std(tensor)

# Compute the standard deviation along axis 0 (column-wise)
std_axis0 = tf.math.reduce_std(tensor, axis=0)

# Compute the standard deviation along axis 1 (row-wise)
std_axis1 = tf.math.reduce_std(tensor, axis=1)

print("Standard Deviation (all elements):", std_all.numpy())
print("Standard Deviation along axis 0 (column-wise):", std_axis0.numpy())
print("Standard Deviation along axis 1 (row-wise):", std_axis1.numpy())

Standard Deviation (all elements): 1.7078252
Standard Deviation along axis 0 (column-wise): [1.5 1.5 1.5]
Standard Deviation along axis 1 (row-wise): [0.8164966 0.8164966]


### 7. Basic Mathematical Functions

In [8]:
import tensorflow as tf

# Define a 2D tensor (3x3)
tensor = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Square Root: Element-wise square root of a tensor.
result = tf.sqrt(tensor)
# Absolute Value: Element-wise absolute value of a tensor.
result = tf.abs(tensor)
# Negative: Element-wise negation of a tensor.
result = tf.negative(tensor)
# Sine, Cosine, Tangent: Element-wise trigonometric functions.
result_sin = tf.sin(tensor)
result_cos = tf.cos(tensor)
result_tan = tf.tan(tensor)

### 8. Comparison Operations

In [10]:
import tensorflow as tf

# Define a 2D tensor (3x3)
tensor_a = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)
tensor_b = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

# Create condition_a and condition_b boolean tensors
condition_a = tf.constant([True, False, True])   # Example boolean tensor 1
condition_b = tf.constant([False, True, True])   # Example boolean tensor 2

# Equal: Element-wise equality comparison of two tensors.
result = tf.equal(tensor_a, tensor_b)
# Not Equal: Element-wise inequality comparison of two tensors.
result = tf.not_equal(tensor_a, tensor_b)
# Greater Than, Less Than: Element-wise comparison of two tensors.
result_gt = tf.greater(tensor_a, tensor_b)
result_lt = tf.less(tensor_a, tensor_b)
# Logical AND, OR: Element-wise logical operations.
result_and = tf.logical_and(condition_a, condition_b)
result_or = tf.logical_or(condition_a, condition_b)

### 9. Clipping and Normalization

In [15]:
import tensorflow as tf

# Define a tensor with values
tensor = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])

# Clip the tensor values to be between 2.0 and 4.0
clipped_tensor = tf.clip_by_value(tensor, clip_value_min=2.0, clip_value_max=4.0)

# Perform L2 normalization along axis 1 (normalize each row)
normalized_x = tf.nn.l2_normalize(tensor, axis=0)

### 10. Handling Missing Values

In [16]:
import tensorflow as tf

# Define a tensor with values
tensor = tf.constant([1.0, 2.0, 3.0, 4.0, 5.0])

# Is NaN, Is Finite: Element-wise checks for NaN (Not a Number) and finite values.
result_isnan = tf.math.is_nan(tensor)
result_isfinite = tf.math.is_finite(tensor)

tf.Tensor([False False False False False], shape=(5,), dtype=bool)
