# Using TensorFlow like NumPy
* TensorFlow can be used in a way similar to NumPy for numerical computations, array manipulations, and mathematical operations. 
* TensorFlow like NumPy allows you to benefit from TensorFlow's powerful features such as `automatic differentiation`, `GPU acceleration`, `distributed computing`, and seamless integration with `deep learning frameworks`. This approach is ideal for scientific computing and building complex machine learning models.

## Tensors and operations

* In TensorFlow, `tensors` are fundamental objects that represent data in the computation graph. They flow through operations, allowing for efficient computation and differentiation.

* Tensors are central to TensorFlow's design, enabling efficient and scalable computation in deep learning models. By understanding how to create and manipulate tensors, you can effectively work with TensorFlow's API to build and train sophisticated machine learning models.

* These tensors will be important when we create `custom cost functions`, `custom metrics`, `custom layers`, and more, so let’s see how to create and manipulate them.

### 1. Creating Tensors
* You can create tensors in TensorFlow just like NumPy arrays:

In [8]:
import tensorflow as tf

# Create a constant tensor
a = tf.constant([[1.0, 2.0], [3.0, 4.0]])

# Create a variable tensor (can be updated)
b = tf.Variable([[1.0, 2.0], [3.0, 4.0]])

# Accessing shape, dtype, and ndim
tensor = tf.constant([[1, 2], [3, 4]])
# shape: Attribute that returns the shape of the tensor.
print(tensor.shape)  # Output: (2, 2)
# dtype: Attribute that returns the data type of the tensor.
print(tensor.dtype)  # Output: <dtype: 'int32'>
# ndim: Method that returns the number of dimensions (or rank) of the tensor.
print(tensor.ndim)  # Output: 2

# Create tensors with specified shape and dtype
zeros_tensor = tf.zeros((3, 3), dtype=tf.float32)
ones_tensor = tf.ones((2, 2), dtype=tf.int32)
random_tensor = tf.random.normal((3, 3), mean=0.0, stddev=1.0, dtype=tf.float32)

(2, 2)
<dtype: 'int32'>
2


### 2. Indexing
* Indexing refers to accessing individual elements within a tensor using specific indices :

In [9]:
import tensorflow as tf

# Define a 2D tensor
tensor_2d = tf.constant([[1, 2, 3],
                          [4, 5, 6]])

# Accessing individual elements
print(tensor_2d[0, 0])  # Output: 1
print(tensor_2d[1, 2])  # Output: 6

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)


### 3. Slicing
* Slicing allows you to extract sub-tensors (slices) from a larger tensor based on specific ranges of indices along each dimension.

In [10]:
# Define a 2D tensor (3x3)
tensor_2d = tf.constant([[1, 2, 3],
                          [4, 5, 6],
                          [7, 8, 9]])

# Slicing along rows and columns
print(tensor_2d[0, :])  # Slice the first row: [1, 2, 3]
print(tensor_2d[:, 1])  # Slice the second column: [2, 5, 8]

# Slicing sub-tensors
print(tensor_2d[1:, :2])  # Slice rows from index 1 onwards and columns up to index 2:
                          # [[4, 5],
                          #  [7, 8]]

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 5 8], shape=(3,), dtype=int32)
tf.Tensor(
[[4 5]
 [7 8]], shape=(2, 2), dtype=int32)


In [11]:
# Define a 3D tensor (3x3x3)
tensor_3d = tf.constant([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])

# Slicing along different dimensions
print(tensor_3d[1, :, :])  # Slice the entire 2nd 'layer' (2nd matrix)
print(tensor_3d[:, 1, 1])  # Slice the (1, 1) element from each 'layer'
print(tensor_3d[0:2, :, 0])  # Slice the first two 'layers' and extract the first column

tf.Tensor(
[[10 11 12]
 [13 14 15]
 [16 17 18]], shape=(3, 3), dtype=int32)
tf.Tensor([ 5 14 23], shape=(3,), dtype=int32)
tf.Tensor(
[[ 1  4  7]
 [10 13 16]], shape=(2, 3), dtype=int32)
